### PR TITLE
Improve dataloader

### PR DESCRIPTION
**Pull request by zpcore**
Integrate dataloader fix from [JackCaoG](https://github.com/JackCaoG)

### CODE REVIEW

**Comment by bhavya01** [comment]
`args.loader_prefetch_size` is used for `MpDeviceLoader`. Do we need to change the prefetch factor? I thought that just changing the number of cpu dataloader workers is enough. If we need to change this, then I suggest using a new arg. Will wait for @JackCaoG to confirm.

**Comment by JackCaoG** [comment]
> `args.loader_prefetch_size` is used for `MpDeviceLoader`. Do we need to change the prefetch factor? I thought that just changing the number of cpu dataloader workers is enough. If we need to change this, then I suggest using a new arg. Will wait for @JackCaoG to confirm.

In my local setup I increase the number of worker by passing a larger `dataloader_num_workers `, and I also set the `loader_prefetch_size` for torch dataloader. We could have a separate config for it but I felt like setting it to be the same as the parallloader's prefect kind of make sense. since it will be
```
torch_loader->parall_loader->device
```
and each loader has a queue for worker to process.

**Review by JackCaoG — APPROVED** [review]

**Comment by bhavya01** [comment]
Would still suggest using a different flag for prefetch factor. It is quite different from the loader_queue in parallel_loader.

In parallel_loader, it means that the number examples we prefetch from torch dataloader. 

In torch dataloader, it means the number of samples prefetched by each dataloader worker https://screenshot.googleplex.com/6rzXyCgyQwtXLGd. If we are using multiple torch dataloader workers, then it could significantly increase the CPU load by increasing the prefetch factor.

**Comment by JackCaoG** [comment]
ok then let's use a different config then

**Review by bhavya01 — APPROVED** [review]

**Pull request merged**
